import React, { Component } from 'react';
import {
  Text,
  View,
  TouchableOpacity,
  Dimensions,
  TextInput
} from 'react-native';

const window = Dimensions.get('window');

export class Receipt extends Component<{}> {


static navigationOptions = {
    title: 'Receipt',
    
  }

  render() {
    return (
      <View style={{backgroundColor:'#633ea5',height:window.height}}>
        <View style={{alignItems:'center',paddingTop:10}}>
          <Text style={{fontSize:20,color:'white'}}>RECEIPT</Text>
        </View>

        <View style={{paddingTop:40,paddingLeft:30}}>
          <Text style={{color:'white',fontSize:24}}>Big Bazaar Inc</Text>
          <Text style={{color:'white',fontSize:12,paddingTop:10}}>10:05 AM, 25 AUGUST, 2017</Text>
          <Text style={{color:'white',fontSize:18,paddingTop:10}}># 99adfs</Text>
          <Text style={{color:'white',fontSize:18,paddingTop:30}}>AMOUNT - 443.15</Text>

           <Text style={{color:'white',fontSize:18,paddingTop:10}}>TAX - 15.66</Text>
            <Text style={{color:'white',fontSize:18,paddingTop:15}}>TOTAL- 457.85</Text>
          <Text style={{color:'white',fontSize:14,paddingTop:40,paddingLeft:34}}>This receipt is generated by Zeta Inc.</Text>
        </View>

      </View>
    );
  }
}

